// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/employees": {
            "get": {
                "description": "Получает список всех преподавателей из БГУИРа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Получить список всех преподавателей",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "Использовать кэш",
                        "name": "useCache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.EmployeeListItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/employees/refresh": {
            "post": {
                "description": "Принудительно обновляет список всех преподавателей из API БГУИРа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Обновить список всех преподавателей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/employees/{urlId}": {
            "get": {
                "description": "Получает информацию о преподавателе по URL ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Получить преподавателя по URL ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL ID преподавателя",
                        "name": "urlId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EmployeeListItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/groups": {
            "get": {
                "description": "Получает список всех групп из БГУИРа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Получить список всех групп",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "Использовать кэш",
                        "name": "useCache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StudentGroupListItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/groups/refresh": {
            "post": {
                "description": "Принудительно обновляет список всех групп из API БГУИРа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Обновить список всех групп",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/groups/{groupNumber}": {
            "get": {
                "description": "Получает информацию о группе по номеру",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Получить группу по номеру",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Номер группы",
                        "name": "groupNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudentGroupListItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/employee/{urlId}": {
            "get": {
                "description": "Получает расписание преподавателя по URL ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Получить расписание преподавателя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL ID преподавателя",
                        "name": "urlId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "Использовать кэш",
                        "name": "useCache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/employee/{urlId}/refresh": {
            "post": {
                "description": "Принудительно обновляет расписание преподавателя из API БГУИРа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Обновить расписание преподавателя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL ID преподавателя",
                        "name": "urlId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/group/{groupNumber}": {
            "get": {
                "description": "Получает расписание группы по номеру группы",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Получить расписание группы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Номер группы",
                        "name": "groupNumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "Использовать кэш",
                        "name": "useCache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/group/{groupNumber}/refresh": {
            "post": {
                "description": "Принудительно обновляет расписание группы из API БГУИРа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Обновить расписание группы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Номер группы",
                        "name": "groupNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/favorites": {
            "get": {
                "description": "Возвращает список всех избранных групп пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "Получить все избранные группы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя (пока используем 'default')",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.FavoriteGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/favorites/{groupNumber}": {
            "post": {
                "description": "Добавляет группу в список избранных для пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "Добавить группу в избранное",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя (пока используем 'default')",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер группы",
                        "name": "group_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет группу из списка избранных для пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "Удалить группу из избранного",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя (пока используем 'default')",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер группы",
                        "name": "group_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/favorites/{groupNumber}/check": {
            "get": {
                "description": "Проверяет, добавлена ли группа в избранное для пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "Проверить, является ли группа избранной",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя (пока используем 'default')",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер группы",
                        "name": "group_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.EmployeeDto": {
            "type": "object",
            "properties": {
                "academicDepartment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "calendarId": {
                    "type": "string"
                },
                "degree": {
                    "type": "string"
                },
                "degreeAbbrev": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fio": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jobPositions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "photoLink": {
                    "type": "string"
                },
                "rank": {
                    "type": "string"
                },
                "urlId": {
                    "type": "string"
                }
            }
        },
        "models.EmployeeListItem": {
            "type": "object",
            "properties": {
                "academicDepartment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "calendarId": {
                    "type": "string"
                },
                "degree": {
                    "type": "string"
                },
                "fio": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "photoLink": {
                    "type": "string"
                },
                "rank": {
                    "type": "string"
                },
                "urlId": {
                    "type": "string"
                }
            }
        },
        "models.FavoriteGroup": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "group_number": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.Schedule": {
            "type": "object",
            "properties": {
                "announcement": {
                    "type": "boolean"
                },
                "auditories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dateLesson": {
                    "type": "string"
                },
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EmployeeDto"
                    }
                },
                "endLessonDate": {
                    "type": "string"
                },
                "endLessonTime": {
                    "type": "string"
                },
                "lessonTypeAbbrev": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "numSubgroup": {
                    "type": "integer"
                },
                "split": {
                    "type": "boolean"
                },
                "startLessonDate": {
                    "type": "string"
                },
                "startLessonTime": {
                    "type": "string"
                },
                "studentGroups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StudentGroup"
                    }
                },
                "subject": {
                    "type": "string"
                },
                "subjectFullName": {
                    "type": "string"
                },
                "weekNumber": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.ScheduleResponse": {
            "type": "object",
            "properties": {
                "employeeDto": {
                    "$ref": "#/definitions/models.EmployeeDto"
                },
                "endDate": {
                    "type": "string"
                },
                "endExamsDate": {
                    "type": "string"
                },
                "exams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Schedule"
                    }
                },
                "schedules": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.Schedule"
                        }
                    }
                },
                "startDate": {
                    "type": "string"
                },
                "startExamsDate": {
                    "type": "string"
                },
                "studentGroupDto": {
                    "$ref": "#/definitions/models.StudentGroupDto"
                }
            }
        },
        "models.StudentGroup": {
            "type": "object",
            "properties": {
                "educationDegree": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "numberOfStudents": {
                    "type": "integer"
                },
                "specialityCode": {
                    "type": "string"
                },
                "specialityName": {
                    "type": "string"
                }
            }
        },
        "models.StudentGroupDto": {
            "type": "object",
            "properties": {
                "calendarId": {
                    "type": "string"
                },
                "course": {
                    "type": "integer"
                },
                "educationDegree": {
                    "type": "integer"
                },
                "facultyAbbrev": {
                    "type": "string"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "specialityAbbrev": {
                    "type": "string"
                },
                "specialityDepartmentEducationFormId": {
                    "type": "integer"
                },
                "specialityName": {
                    "type": "string"
                }
            }
        },
        "models.StudentGroupListItem": {
            "type": "object",
            "properties": {
                "calendarId": {
                    "type": "string"
                },
                "course": {
                    "type": "integer"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "specialityDepartmentEducationFormId": {
                    "type": "integer"
                },
                "specialityName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Schedluer API",
	Description:      "API для работы с расписанием БГУИР",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
